### ISSUE TITLE
Error on clicking any bar in "All Bids" bar chart

### ISSUE THREAD

**Issue by brian-brian** [LoneRifle/fcviz#1]
Gives error: "Uncaught TypeError: target.match is not a function"
-> cannot select elements in the pie chart or scroll the Lender list next to the pie chart

To reproduce:
log in to Funding Circle
visit an auction page
select All bids
wait for the bar chart to load
click any bar in the chart
the bar turns blue and the pie chart appears
the error message "Uncaught TypeError: target.match is not a function" appears in the Chrome debugging console
click any element in the pie chart: nothing happens
try moving the scroll bars on the Lender list adjacent to the pie chart: nothing happens

**Comment by LoneRifle** [comment]
Fixed with 0ec4914. For what it's worth, the error message in the console is a bit of a red herring and should not interfere with the operation of the plugin

**Comment by brian-brian** [comment]
Many thanks for fixing this bug LoneRifle, and for all your work producing fcviz. It's a great visualisation tool.
