### ISSUE TITLE
Loan ignore list

### ISSUE THREAD

**Issue by SteveWooding** [LoneRifle/fcviz#2]
Hello,

Since I can't find any other contact details, I thought I would contact you via a GitHub issue.

I'm looking to add a feature to the Funding Circle website that would enable a user to add a loan to an ignore list. This would mean loans in the ignore list would not show up in the secondary market (this is where I mainly want this anyway). The ignore list would probably be stored in Chrome's local storage. Could also have an import/export feature for backup and portability reasons. 

Do you think such a feature would be suitable to be incorporated into your plug-in (via a pull request by me), or do you think I should write a separate plugin?

I look forward to reading your answer.

Regards,

Steve.

**Comment by LoneRifle** [comment]
Hello,

I'm trying to avoid holding state in FCViz as I'm wary of holding data that might relate to a user, since that would mean it would fall under FCA's purview and would complicate any dealings I might have with Funding Circle. I however concede that I am taking an ultra-conservative stance bordering on paranoia, so if you start a new project, I'll be happy to contribute and coordinate with you.

**Comment by SteveWooding** [comment]
That's fair enough. You could also argue it is far enough removed from the purpose of your extension, that it should be a separate extension. I see Google are keen to keep each extension have a single purpose.

Thanks for the offer of help. I'll be in touch if I get a new project started.

Regards,

Steve.

**Comment by SteveWooding** [comment]
Hi there,

I've got something working now. Here's the link to the project: https://github.com/SteveWooding/fc-ignore

It works up to a point, but if you change any of the loan filter settings, the table reloads and my ignore buttons don't get re-rendered (which makes sense). This issue is recorded here: https://github.com/SteveWooding/fc-ignore/issues/1

I've been trying to detect when the table is refreshed, so that I can re-run my ignore functions, but I've been unable to get anything working. I was wondering if you had any insight to this problem? Any ideas would be very welcome.

Cheers,

Steve.
