### ISSUE TITLE
Repayment peeking link for A+ & A loans becomes non-functional

### ISSUE THREAD

**Issue by gl517** [LoneRifle/fcviz#3]
I have been unable to identify what triggers it, but the peeking by hovering over the "?" icon fails to function for me more often than not. I only notice it when filtering on A+, or A+ and A loans. 
Refreshing the page brings the functionality back, but when chasing popular loan parts this delay means missing the purchase, so I now ignore the function, which is a loss.
I notice that A+ property loans tend to have longer titles, which leads to the "?" icon being shifted to the right. I don't know if this has something to do with it.

**Comment by LoneRifle** [comment]
Heya, appears to work for me (no reloading done):
![A loan repayment peeking](https://cdn.pbrd.co/images/bXdT2Ky.png)

The code that retrieves the repayment details is blind to risk grade, so I don't expect the risk rating of the loan to affect functionality. There might be a few things I can do to try to tweak the reliability and display of the tooltip though, so let me see what I can do.

**Comment by LoneRifle** [comment]
This should be fixed with 640e33d
